apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "limit-range"
  namespace: wiki
spec:
  limits:
    - type: "Container"
      default:
        cpu: "200m"
        memory: 256Mi
      defaultRequest:
        cpu: "200m"
        memory: 256Mi
