apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: wiki
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    requests.storage: 10Gi

